/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef WORD2VEC_PRIVATE_H
#define WORD2VEC_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.2.0.0"
#define VER_MAJOR	0
#define VER_MINOR	2
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	""
#define FILE_VERSION	"0.2.0.0"
#define FILE_DESCRIPTION	"Google word2vec for Windows"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"0.2.0.0"

#endif /*WORD2VEC_PRIVATE_H*/
